---
- name: Ping
  ansible.builtin.uri:
    url: "{{ runner_base_url }}/ping"
    method: GET
    return_content: true

- name: Log in
  ansible.builtin.uri:
    url: "{{ runner_base_url }}/login"
    method: POST
    body_format: json
    body:
      name: "{{ runner_api_user }}"
      password: "{{ runner_api_user_password }}"
    status_code: 204
  register: runner_login

- name: Get projects
  ansible.builtin.uri:
    url: "{{ runner_base_url }}/projects"
    method: GET
    return_content: true
    headers:
      Cookie: "{{ runner_login.cookies_string }}"
