---
- name: Ping
  ansible.builtin.uri:
    url: "{{ runner_base_url }}/ping"
    method: GET
    return_content: true

- name: Log in
  ansible.builtin.uri:
    url: "{{ runner_base_url }}/auth/login"
    method: POST
    body_format: json
    body:
      auth: "{{ runner_api_user }}"
      password: "{{ runner_api_user_password }}"
    status_code: 204
  register: runner_login

- name: Get projects
  ansible.builtin.uri:
    url: "{{ runner_base_url }}/projects"
    method: GET
    return_content: true
    headers:
      Cookie: "{{ runner_login.cookies_string }}"
  register: runner_projects

- name: Get tasks
  ansible.builtin.uri:
    url: "{{ runner_base_url }}/project/{{ ((runner_projects.content | from_json) | selectattr('name', 'equalto', 'test') | first).id }}/tasks"
    headers:
      Cookie: "{{ runner_login.cookies_string }}"
  register: runner_tasks

- name: Run task
  ansible.builtin.uri:
    url: "{{ runner_base_url }}/project/{{ ((runner_projects.content | from_json) | selectattr('name', 'equalto', 'test') | first).id }}/tasks"
    method: POST
    body_format: json
    body:
      template_id: "{{ runner_tasks.json[0].template_id }}" 
      debug: false
      dry_run: false
      playbook: "{{ runner_tasks.json[0].tpl_playbook }}"
      environment: "{{ runner_tasks.json[0].environment }}"
    headers:
      Cookie: "{{ runner_login.cookies_string }}"
